apiVersion: apps/v1
kind: Deployment
metadata:
  name: event
  labels:
    app: event
spec:
  replicas: 3
  selector:
    matchLabels:
      app: event
  template:
    metadata:
      labels:
        app: event
    spec:
      containers:
      - name: main
        image: 076508105214.dkr.ecr.ap-northeast-2.amazonaws.com/bastion:event3
        ports:
        - containerPort: 8888

