apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: main
spec:
  replicas: 3
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main
        image: 076508105214.dkr.ecr.ap-northeast-2.amazonaws.com/bastion:2 
        ports:
        - containerPort: 8888
